# Generated by Django 5.2.3 on 2025-07-13 00:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='titre',
            field=models.CharField(default="Nom de l'intervention", max_length=255, verbose_name="Titre de l'intervention"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du fichier')),
                ('fichier', models.FileField(upload_to='pieces_jointes/', verbose_name='Fichier')),
                ('type_fichier', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('video', 'Vidéo'), ('autre', 'Autre')], default='document', max_length=20, verbose_name='Type de fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='core.intervention', verbose_name='Intervention')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
    ]
