# Generated by Django 5.2.3 on 2025-07-13 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_intervention_date_creation_intervention_titre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_intervention', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'intervention")),
                ('date_debut', models.DateTimeField(verbose_name='Date et heure de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('motif_intervention', models.TextField(verbose_name="Motif de l'intervention")),
                ('conditions_intervention', models.TextField(verbose_name="Conditions d'intervention")),
                ('etapes_diagnostic', models.TextField(verbose_name='Étapes de diagnostic')),
                ('travaux_effectues', models.TextField(verbose_name='Travaux effectués')),
                ('verification_post_intervention', models.TextField(verbose_name='Vérification post-intervention')),
                ('ressources_utilisees', models.TextField(verbose_name='Ressources utilisées')),
                ('duree_totale', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Durée totale (heures)')),
                ('etat_final', models.CharField(choices=[('resolu', 'Résolu'), ('partiellement', 'Partiellement résolu'), ('non_resolu', 'Non résolu')], max_length=20, verbose_name='État final')),
                ('anomalies_restantes', models.TextField(blank=True, verbose_name='Anomalies restantes')),
                ('recommandations', models.TextField(blank=True, verbose_name='Recommandations')),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut de validation')),
                ('commentaire_validateur', models.TextField(blank=True, verbose_name='Commentaire du validateur')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='core.intervention', verbose_name='Intervention')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validateur')),
            ],
            options={
                'verbose_name': "Rapport d'intervention",
                'verbose_name_plural': "Rapports d'intervention",
            },
        ),
    ]
