# Generated by Django 5.2.3 on 2025-07-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_intervention_cree_par_alter_intervention_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/', verbose_name='Photo de profil'),
        ),
    ]
