# Generated by Django 5.2.3 on 2025-07-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_utilisateur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='difficultes',
            field=models.TextField(blank=True, verbose_name='Difficultés rencontrées'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='etat_intervention',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('resolue', 'Résolue'), ('non_resolue', 'Non résolue')], default='en_attente', max_length=20, verbose_name="État de l'intervention"),
        ),
        migrations.AddField(
            model_name='intervention',
            name='heure_arrivee',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée"),
        ),
        migrations.AddField(
            model_name='intervention',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de départ'),
        ),
    ]
