# Generated by Django 5.2.3 on 2025-07-15 16:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_intervention_difficultes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapportintervention',
            options={},
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='anomalies_restantes',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='commentaire_validateur',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='conditions_intervention',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='duree_totale',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='etapes_diagnostic',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='etat_final',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='motif_intervention',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='numero_intervention',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='recommandations',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='statut_validation',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='travaux_effectues',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='validateur',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='verification_post_intervention',
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='motif_rejet',
            field=models.TextField(blank=True, verbose_name='Motif du rejet'),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='objectif',
            field=models.TextField(blank=True, verbose_name="Objectif de l'intervention"),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='statut',
            field=models.CharField(choices=[('embrouillant', 'Brouillon'), ('soumis', 'Soumis'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='embrouillant', max_length=20),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='travaux_realises',
            field=models.TextField(blank=True, verbose_name='Travaux réalisés'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='intervention',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='core.intervention'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='ressources_utilisees',
            field=models.TextField(blank=True, verbose_name='Ressources utilisées'),
        ),
        migrations.CreateModel(
            name='RapportFichierJoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='rapports/fichiers/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_joints', to='core.rapportintervention')),
            ],
        ),
        migrations.CreateModel(
            name='RapportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rapports/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('type_image', models.CharField(choices=[('avant', 'Avant'), ('apres', 'Après')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.rapportintervention')),
            ],
        ),
    ]
