# Generated by Django 5.2.3 on 2025-07-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_rapportintervention_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportintervention',
            name='conditions_intervention',
            field=models.TextField(blank=True, verbose_name="Conditions d'intervention"),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='motif_intervention',
            field=models.TextField(blank=True, verbose_name="Motif de l'intervention"),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20),
        ),
    ]
