# Generated by Django 5.2.3 on 2025-07-15 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rapportintervention_conditions_intervention_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='compte_rendu',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='lieu',
        ),
        migrations.AddField(
            model_name='intervention',
            name='date_echeance',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date au plus tard de réalisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='priorite',
            field=models.CharField(choices=[('normale', 'Normale'), ('urgente', 'Urgente')], default='normale', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='ressources_utilisees',
            field=models.TextField(blank=True, verbose_name='Ressources à utiliser'),
        ),
    ]
