# Generated by Django 5.2.3 on 2025-07-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_intervention_compte_rendu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapportintervention',
            name='conditions_intervention',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='motif_intervention',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='objectif',
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='ameliorations_a_faire',
            field=models.TextField(blank=True, verbose_name='Améliorations à faire'),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='resultat_final',
            field=models.TextField(blank=True, verbose_name='Résultat final'),
        ),
    ]
