# Generated by Django 5.2.3 on 2025-07-17 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_rapportintervention_conditions_intervention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportintervention',
            name='commentaire_validation',
            field=models.TextField(blank=True, verbose_name='Commentaire de validation'),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='rejete_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_rejetes', to=settings.AUTH_USER_MODEL, verbose_name='Rejeté par'),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='valide_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
    ]
