# Generated by Django 5.2.3 on 2025-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rapportintervention_commentaire_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de début'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin'),
        ),
    ]
