# Generated by Django 5.2.3 on 2025-07-19 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_intervention_date_debut_intervention_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='date_retard',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de début du retard'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='duree_retard',
            field=models.DurationField(blank=True, null=True, verbose_name='Durée du retard'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='en_retard',
            field=models.BooleanField(default=False, verbose_name='En retard'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='motif_retard',
            field=models.TextField(blank=True, verbose_name='Motif du retard'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='retard_resolu',
            field=models.BooleanField(default=False, verbose_name='Retard résolu'),
        ),
        migrations.CreateModel(
            name='RetardIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_retard', models.CharField(choices=[('debut', 'Retard au début'), ('fin', 'Retard à la fin'), ('duree', 'Dépassement de durée'), ('planification', 'Problème de planification'), ('technique', 'Problème technique'), ('client', 'Problème client'), ('autre', 'Autre')], max_length=20, verbose_name='Type de retard')),
                ('date_debut_retard', models.DateTimeField(verbose_name='Date de début du retard')),
                ('date_fin_retard', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin du retard')),
                ('duree_retard', models.DurationField(blank=True, null=True, verbose_name='Durée du retard')),
                ('motif', models.TextField(verbose_name='Motif du retard')),
                ('impact', models.TextField(blank=True, verbose_name='Impact sur la mission')),
                ('actions_correctives', models.TextField(blank=True, verbose_name='Actions correctives')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('resolu', models.BooleanField(default=False, verbose_name='Résolu')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retards', to='core.intervention', verbose_name='Intervention')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retards_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': "Retard d'intervention",
                'verbose_name_plural': "Retards d'intervention",
            },
        ),
    ]
